-- ==============================
-- 0) ĐỊNH NGHĨA CÁC KIỂU ENUM
-- ==============================
DO $$ BEGIN
    CREATE TYPE exam_type_enum AS ENUM ('ESSAY', 'MCQ', 'BOTH');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trạng thái đăng ký thi: Chờ duyệt, Đã duyệt, Từ chối, Đã hủy
DO $$ BEGIN
    CREATE TYPE registration_status_enum AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Cấp độ chứng chỉ cán bộ chấm thi: Sơ cấp, Trung cấp, Cao cấp
DO $$ BEGIN
    CREATE TYPE certification_level_enum AS ENUM ('JUNIOR', 'SENIOR', 'EXPERT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trình độ chấm môn: Cơ bản, Nâng cao, Chuyên gia
DO $$ BEGIN
    CREATE TYPE qualification_level_enum AS ENUM ('BASIC', 'ADVANCED', 'EXPERT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Loại câu hỏi trắc nghiệm: Nhiều lựa chọn, Đúng/Sai
DO $$ BEGIN
    CREATE TYPE question_type_enum AS ENUM ('MULTIPLE_CHOICE', 'TRUE_FALSE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Độ khó câu hỏi: Dễ, Trung bình, Khó
DO $$ BEGIN
    CREATE TYPE difficulty_level_enum AS ENUM ('EASY', 'MEDIUM', 'HARD');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trạng thái phiên thi: Đang làm, Đã nộp, Đã chấm, Đã hủy
DO $$ BEGIN
    CREATE TYPE attempt_status_enum AS ENUM ('IN_PROGRESS', 'SUBMITTED', 'GRADED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Loại cảnh báo gian lận: Chuyển tab, Đăng nhập nhiều nơi, Không hoạt động, Hành vi khả nghi
DO $$ BEGIN
    CREATE TYPE alert_type_enum AS ENUM ('TAB_SWITCH', 'MULTI_LOGIN', 'INACTIVITY', 'SUSPICIOUS_ACTIVITY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Hành động với đáp án: Đã chọn, Đã bỏ chọn (tracking lịch sử thay đổi)
DO $$ BEGIN
    CREATE TYPE history_action_enum AS ENUM ('SELECTED', 'DESELECTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trạng thái khối chấm: Chờ, Đã giao, Đã chấm, Hoàn thành, Lỗi
DO $$ BEGIN
    CREATE TYPE block_status_enum AS ENUM ('PENDING', 'ASSIGNED', 'GRADED', 'COMPLETED', 'ERROR');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trạng thái phân công chấm: Đã giao, Đang làm, Hoàn thành, Quá hạn
DO $$ BEGIN
    CREATE TYPE assignment_status_enum AS ENUM ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Mức độ ưu tiên: Thấp, Trung bình, Cao
DO $$ BEGIN
    CREATE TYPE priority_enum AS ENUM ('LOW', 'MEDIUM', 'HIGH');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Xếp loại điểm: A (Xuất sắc), B (Giỏi), C (Khá), D (Trung bình), F (Yếu)
DO $$ BEGIN
    CREATE TYPE grade_enum AS ENUM ('A', 'B', 'C', 'D', 'F');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trạng thái điểm cuối: Nháp, Chính thức, Đã công bố, Đang khiếu nại
DO $$ BEGIN
    CREATE TYPE final_status_enum AS ENUM ('DRAFT', 'FINAL', 'PUBLISHED', 'APPEALED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Loại thao tác import/export: Nhập, Xuất
DO $$ BEGIN
    CREATE TYPE operation_type_enum AS ENUM ('IMPORT', 'EXPORT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trạng thái thao tác: Đang xử lý, Thành công, Thất bại, Một phần
DO $$ BEGIN
    CREATE TYPE operation_status_enum AS ENUM ('PROCESSING', 'SUCCESS', 'FAILED', 'PARTIAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ==============================
-- 1) HÀM TRIGGER - Tự động cập nhật updated_at
-- ==============================
-- Hàm này sẽ được gọi bởi trigger để tự động cập nhật
-- cột updated_at mỗi khi có UPDATE trên bảng
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = CURRENT_TIMESTAMP;  -- Gán thời gian hiện tại
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =====================================================
-- 2) VAI TRÒ & NGƯỜI DÙNG
-- =====================================================
-- Bảng vai trò (Admin, Giám khảo, Thí sinh, Giám thị, Quản lý dữ liệu)
CREATE TABLE IF NOT EXISTS roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID tự tăng
    role_name VARCHAR(50) UNIQUE NOT NULL,  -- Tên vai trò duy nhất (admin, examiner, candidate...)
    description TEXT,  -- Mô tả vai trò
    permissions JSONB,  -- Quyền hạn dạng JSON: {"grade": true, "view_reports": true}
    is_active BOOLEAN DEFAULT TRUE,  -- Còn sử dụng hay không
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Thời điểm tạo
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Tự động cập nhật qua trigger
);

-- Bảng người dùng (Tài khoản hệ thống)
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID tự tăng
    username VARCHAR(50) UNIQUE NOT NULL,  -- Tên đăng nhập duy nhất
    password VARCHAR(255) NOT NULL,  -- Mật khẩu đã hash (bcrypt)
    full_name VARCHAR(100) NOT NULL,  -- Họ và tên đầy đủ
    email VARCHAR(100) UNIQUE,  -- Email duy nhất
    phone VARCHAR(15),  -- Số điện thoại
    role_id INT NOT NULL REFERENCES roles(role_id) ON DELETE RESTRICT,  -- Vai trò (FK)
    is_active BOOLEAN DEFAULT TRUE,  -- Tài khoản còn hoạt động không
    last_login TIMESTAMP NULL,  -- Lần đăng nhập gần nhất
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Thời điểm tạo
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Tự động cập nhật qua trigger
);


-- =====================================================
-- 3) MÔN THI
-- =====================================================
-- Bảng danh sách các môn thi (Toán, Lý, Hóa, Sinh, Anh...)
CREATE TABLE IF NOT EXISTS subjects (
    subject_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID tự tăng
    subject_code VARCHAR(20) UNIQUE NOT NULL,  -- Mã môn duy nhất (MATH, PHYS, CHEM...)
    subject_name VARCHAR(100) NOT NULL,  -- Tên môn hiển thị
    description TEXT,  -- Mô tả chi tiết môn thi
    is_active BOOLEAN DEFAULT TRUE,  -- Môn còn mở thi không
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Thời điểm tạo
);


-- =====================================================
-- 4) THÍ SINH
-- =====================================================
-- Bảng thông tin thí sinh (mở rộng từ users)
CREATE TABLE IF NOT EXISTS candidates (
    candidate_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID tự tăng
    candidate_code VARCHAR(20) UNIQUE NOT NULL,  -- Số báo danh duy nhất (TS001, TS002...)
    user_id INT NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,  -- Liên kết 1-1 với users
    date_of_birth DATE NOT NULL,  -- Ngày sinh (để đối chiếu khi scan phách)
    identity_card VARCHAR(20) UNIQUE,  -- Số CMND/CCCD
    address TEXT,  -- Địa chỉ liên hệ
    is_active BOOLEAN DEFAULT TRUE,  -- Thí sinh còn hoạt động không
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Thời điểm tạo
);

-- Bảng đăng ký thi của thí sinh
CREATE TABLE IF NOT EXISTS candidate_exam_registrations (
    registration_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID đăng ký
    candidate_id INT NOT NULL REFERENCES candidates(candidate_id) ON DELETE CASCADE,  -- Thí sinh nào
    subject_id INT NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,  -- Môn gì
    exam_type exam_type_enum NOT NULL,  -- Loại thi: Tự luận/Trắc nghiệm/Cả hai
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Ngày đăng ký
    status registration_status_enum DEFAULT 'PENDING',  -- Trạng thái: Chờ/Đã duyệt/Từ chối/Hủy
    approved_by INT NULL REFERENCES users(user_id) ON DELETE SET NULL,  -- Người duyệt
    approved_at TIMESTAMP NULL,  -- Thời điểm duyệt
    rejection_reason TEXT NULL,  -- Lý do từ chối (nếu có)
    exam_session VARCHAR(50) NULL,  -- Ca thi (Ca 1, Ca 2...)
    exam_room VARCHAR(50) NULL,  -- Phòng thi (P101, P102...)
    seat_number VARCHAR(10) NULL,  -- Số ghế (A01, B02...)
    notes TEXT NULL,  -- Ghi chú khác
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Thời điểm tạo
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Tự động cập nhật qua trigger
    CONSTRAINT unique_candidate_subject UNIQUE (candidate_id, subject_id)  -- 1 thí sinh chỉ đăng ký 1 lần/môn
);


-- =====================================================
-- 5) CÁN BỘ CHẤM THI
-- =====================================================
-- Bảng thông tin cán bộ chấm thi (mở rộng từ users)
CREATE TABLE IF NOT EXISTS examiners (
    examiner_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID tự tăng
    examiner_code VARCHAR(20) UNIQUE NOT NULL,  -- Mã cán bộ (CB001, CB002...)
    user_id INT NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,  -- Liên kết 1-1 với users
    specialization VARCHAR(100),  -- Chuyên môn (Toán học, Vật lý...)
    experience_years INT DEFAULT 0,  -- Số năm kinh nghiệm chấm thi
    certification_level certification_level_enum DEFAULT 'JUNIOR',  -- Cấp độ: Sơ cấp/Trung cấp/Cao cấp
    is_active BOOLEAN DEFAULT TRUE,  -- Còn hoạt động không
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Thời điểm tạo
);

-- Bảng môn chấm của cán bộ (1 cán bộ có thể chấm nhiều môn)
CREATE TABLE IF NOT EXISTS examiner_subjects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID tự tăng
    examiner_id INT NOT NULL REFERENCES examiners(examiner_id) ON DELETE CASCADE,  -- Cán bộ nào
    subject_id INT NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,  -- Môn nào
    is_primary BOOLEAN DEFAULT FALSE,  -- Có phải môn chính không
    qualification_level qualification_level_enum DEFAULT 'BASIC',  -- Trình độ: Cơ bản/Nâng cao/Chuyên gia
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Thời điểm tạo
    CONSTRAINT unique_examiner_subject UNIQUE (examiner_id, subject_id)  -- 1 cán bộ + 1 môn là duy nhất
);


-- =====================================================
-- 6) ESSAY EXAMS
-- =====================================================
-- Bảng đề thi tự luận: cấu hình đề, thời lượng, tổng điểm
CREATE TABLE IF NOT EXISTS exam_essay (
    essay_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- ID đề thi tự luận
    exam_code VARCHAR(20) UNIQUE NOT NULL,                           -- Mã đề (in trên phách)
    exam_title VARCHAR(200) NOT NULL,                                -- Tiêu đề đề thi hiển thị
    subject_id INT NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,  -- Môn thi (FK)
    total_questions INT NOT NULL,                                    -- Tổng số câu hỏi tự luận
    total_score DECIMAL(5,2) NOT NULL,                               -- Tổng điểm tối đa của đề
    time_limit INT NOT NULL,                                         -- Thời gian làm bài (phút)
    instructions TEXT,                                               -- Hướng dẫn làm bài cho thí sinh
    answer_sheet_template TEXT,                                      -- Mẫu phiếu trả lời (nếu có)
    is_active BOOLEAN DEFAULT TRUE,                                  -- Đề còn được sử dụng không
    created_by INT NOT NULL REFERENCES users(user_id),               -- Người tạo đề (user)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);

-- Danh sách câu hỏi của đề tự luận: điểm tối đa, gợi ý đáp án, tiêu chí chấm
CREATE TABLE IF NOT EXISTS essay_questions (
    question_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- ID câu hỏi tự luận
    essay_id INT NOT NULL REFERENCES exam_essay(essay_id) ON DELETE CASCADE,  -- Thuộc đề tự luận nào
    question_number INT NOT NULL,                                    -- Số thứ tự câu hỏi trong đề
    question_text TEXT NOT NULL,                                     -- Nội dung câu hỏi
    max_score DECIMAL(4,2) NOT NULL,                                 -- Điểm tối đa cho câu này
    sample_answer TEXT,                                              -- Bài/ý trả lời mẫu (tham khảo)
    grading_criteria JSONB,                                          -- Tiêu chí chấm chi tiết (JSONB)
    estimated_time INT,                                              -- Thời gian dự kiến cho câu (phút)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                  -- Thời điểm tạo
    CONSTRAINT unique_essay_question UNIQUE (essay_id, question_number)
);


-- =====================================================
-- 7) MCQ BANK & EXAMS
-- =====================================================
-- Ngân hàng câu hỏi trắc nghiệm theo từng môn (bị thừa -- câu hỏi không liên kết vs đề thi mà bank không liên kết vs đề thi để xuất đề )
-- CREATE TABLE IF NOT EXISTS question_bank (
--     bank_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- ID ngân hàng câu hỏi
--     bank_name VARCHAR(100) NOT NULL,                                 -- Tên ngân hàng (VD: Ngân hàng Toán 2025)
--     subject_id INT NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT, -- Môn thi (FK)
--     description TEXT,                                                -- Mô tả/ghi chú
--     total_questions INT DEFAULT 0,                                   -- Tổng số câu đang có (thống kê)
--     is_active BOOLEAN DEFAULT TRUE,                                  -- Còn sử dụng không
--     created_by INT NOT NULL REFERENCES users(user_id),               -- Người tạo
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
-- );

-- Cấu hình đề thi trắc nghiệm (số câu, tổng điểm)
CREATE TABLE IF NOT EXISTS exam_mcq (
    mcq_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         -- ID đề trắc nghiệm
    exam_code VARCHAR(20) UNIQUE NOT NULL,                           -- Mã đề trắc nghiệm
    exam_title VARCHAR(200) NOT NULL,                                -- Tiêu đề đề thi
    subject_id INT NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT, -- Môn thi (FK)
    total_questions INT NOT NULL,                                    -- Tổng số câu
    total_score DECIMAL(5,2) NOT NULL,                               -- Tổng điểm đề
    link_pdf VARCHAR(500),                                           -- Link PDF đề thi (nếu in/phát hành)
    is_active BOOLEAN DEFAULT TRUE,                                  -- Đề còn hiệu lực không
    created_by INT NOT NULL REFERENCES users(user_id),               -- Người tạo
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);

-- Câu hỏi trắc nghiệm: loại câu, độ khó, điểm, giải thích  ----- Các câu hỏi cx 1 đề thi sẽ cx 1 mã đề
CREATE TABLE IF NOT EXISTS mcq_questions (
    question_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- ID câu hỏi trắc nghiệm
    mcq_id INT NOT NULL REFERENCES exam_mcq(mcq_id) ON DELETE CASCADE, -- Thuộc đề thi nào    ---------- vừa sửa
    question_text TEXT NOT NULL,                                     -- Nội dung câu hỏi
    question_type question_type_enum NOT NULL,                       -- Loại: Multiple choice/True-False
    difficulty_level difficulty_level_enum DEFAULT 'MEDIUM',         -- Độ khó mặc định Trung bình
    score DECIMAL(4,2) DEFAULT 1.00,                                 -- Điểm câu hỏi               ------------ thiết lập trong đề thi
    explanation TEXT,                                                -- Giải thích/diễn giải đáp án
    usage_count INT DEFAULT 0,                                       -- Số lần đã đưa vào đề
    is_active BOOLEAN DEFAULT TRUE,                                  -- Còn sử dụng không
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);

-- Đáp án của câu hỏi trắc nghiệm (một câu có nhiều đáp án)
CREATE TABLE IF NOT EXISTS mcq_answers (
    answer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- ID đáp án
    question_id INT NOT NULL REFERENCES mcq_questions(question_id) ON DELETE CASCADE, -- Thuộc câu hỏi nào
    answer_text TEXT NOT NULL,                                       -- Nội dung đáp án
    is_correct BOOLEAN DEFAULT FALSE,                                -- Có phải đáp án đúng hay không
    answer_order INT NOT NULL,                                       -- Thứ tự hiển thị đáp án (A/B/C/D)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);


-- Thiết lập ca thi trắc nghiệm   ----------- Khi thiết lập sẽ chọn 1 đề thi trong ngân hàng đề và thiết lập các thông tin khác
CREATE TABLE IF NOT EXISTS exam_schedule (
    id_schedule INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcq_id INT NOT NULL REFERENCES exam_mcq(mcq_id) ON DELETE CASCADE,
    schedule_code TEXT NOT NULL UNIQUE,                   -- Mã ca thi (ví dụ: "CA001" hoặc "MATH-EXAM-A")
    schedule_password TEXT,                               -- Mật khẩu ca thi (có thể null nếu không yêu cầu)
    total_attempts INT DEFAULT 1,                         -- Giới hạn số lần làm bài/thi sinh
    shuffle_questions BOOLEAN DEFAULT TRUE,               -- Xáo trộn thứ tự câu hỏi
    shuffle_answers BOOLEAN DEFAULT TRUE,                 -- Xáo trộn thứ tự đáp án
    time_limit INT NOT NULL,                              -- Thời gian làm bài (phút)
    time_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP         -- Thời gian bắt đầu thi
);


-- =====================================================
-- 8) MCQ ATTEMPTS
-- =====================================================
-- Phiên làm bài trắc nghiệm của thí sinh: trạng thái, điểm, thời gian, thiết bị  ---- liên kết vs bảng ca thi sẽ lưu lại các bài làm của thí sinh trong ca thi đó
CREATE TABLE IF NOT EXISTS mcq_attempts (
    attempt_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- ID phiên thi trắc nghiệm
    candidate_id INT NOT NULL REFERENCES candidates(candidate_id) ON DELETE RESTRICT, -- Thí sinh
    id_schedule INT NOT NULL REFERENCES exam_schedule(id_schedule) ON DELETE RESTRICT, -- Mã ca thi    -------------------------- Vừa sửa
    registration_id INT NOT NULL REFERENCES candidate_exam_registrations(registration_id) ON DELETE RESTRICT, -- Bản đăng ký
    computer_id VARCHAR(50),                                         -- Mã máy/thiết bị (nếu có)
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                  -- Bắt đầu làm bài
    submitted_at TIMESTAMP NULL,                                     -- Thời điểm nộp bài
    status attempt_status_enum DEFAULT 'IN_PROGRESS',                -- Trạng thái phiên thi
    total_score DECIMAL(5,2) DEFAULT 0.00,                           -- Tổng điểm đạt được
    count_question_correct INT DEFAULT 0,                            -- Số câu đúng
    question_correct_rate DECIMAL(5,2) DEFAULT 0.00,                 -- Tỉ lệ đúng (%)
    time_spent INT DEFAULT 0,                                        -- Thời gian làm (giây/phút tùy chuẩn)
    ip_address VARCHAR(45),                                          -- Địa chỉ IP truy cập
    browser_info TEXT,                                               -- Thông tin trình duyệt/thiết bị
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);

-- Câu trả lời trong phiên thi: IDs đáp án chọn (JSONB), tính điểm và tính đúng/sai
CREATE TABLE IF NOT EXISTS mcq_attempt_answers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,             -- ID bản ghi trả lời
    attempt_id INT NOT NULL REFERENCES mcq_attempts(attempt_id) ON DELETE CASCADE, -- Phiên thi
    question_id INT NOT NULL REFERENCES mcq_questions(question_id) ON DELETE RESTRICT, -- Câu hỏi
    selected_answer_ids JSONB NOT NULL,                              -- Mảng ID đáp án được chọn (JSONB)
    is_correct BOOLEAN DEFAULT FALSE,                                -- Câu trả lời có đúng không
    score_awarded DECIMAL(4,2) DEFAULT 0.00,                         -- Điểm đạt cho câu hỏi này
    answered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                 -- Thời điểm trả lời
    CONSTRAINT unique_attempt_question UNIQUE (attempt_id, question_id)
);


-- =====================================================
-- 9) CẢNH BÁO GIAN LẬN & LỊCH SỬ ĐÁP ÁN (CẢI TIẾN)
-- =====================================================
-- Bảng cảnh báo gian lận (BỎ UNIQUE để 1 attempt có thể có nhiều cảnh báo)
CREATE TABLE IF NOT EXISTS cheating_alerts (
    alert_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID cảnh báo
    attempt_id INT NOT NULL REFERENCES mcq_attempts(attempt_id) ON DELETE CASCADE,  -- Phiên thi nào
    alert_type alert_type_enum NOT NULL,  -- Loại: Chuyển tab/Đa đăng nhập/Không hoạt động/Khả nghi
    alert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Thời điểm phát hiện
    return_to_exam TIMESTAMP NULL,  -- Thời điểm quay lại làm bài
    description TEXT,  -- Mô tả chi tiết vi phạm
    resolved_by INT NULL REFERENCES users(user_id) ON DELETE SET NULL,  -- Giám thị xử lý
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Thời điểm tạo bản ghi
);

-- Bảng lịch sử thay đổi đáp án (TRACKING HÀNH VI THÍ SINH)
-- Ghi lại mỗi lần thí sinh chọn/bỏ chọn đáp án → phân tích sau
CREATE TABLE IF NOT EXISTS history_answers (
    history_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID lịch sử
    attempt_id INT NOT NULL REFERENCES mcq_attempts(attempt_id) ON DELETE CASCADE,  -- Phiên thi nào
    question_id INT NOT NULL REFERENCES mcq_questions(question_id) ON DELETE RESTRICT,  -- Câu hỏi nào
    answer_id INT NOT NULL REFERENCES mcq_answers(answer_id) ON DELETE RESTRICT,  -- Đáp án nào
    action history_action_enum NOT NULL,  -- Hành động: SELECTED (chọn) / DESELECTED (bỏ chọn)
    action_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Thời điểm hành động
    is_correct BOOLEAN DEFAULT FALSE  -- Đáp án có đúng không (để phân tích: chọn đúng → đổi sai)
);


-- =====================================================
-- 10) PAPER CODES & SCANNED PAPERS
-- =====================================================
-- Mã phách: ẩn danh thông tin thí sinh khi chấm tự luận
CREATE TABLE IF NOT EXISTS paper_codes (
    code_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- ID mã phách
    original_candidate_id INT NOT NULL REFERENCES candidates(candidate_id) ON DELETE RESTRICT, -- Thí sinh gốc
    anonymous_code VARCHAR(20) UNIQUE NOT NULL,                      -- Mã phách ẩn danh
    is_used BOOLEAN DEFAULT FALSE,                                   -- Đã sử dụng gắn với bài thi chưa
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);

-- Bài thi tự luận đã scan: file gốc, file xử lý, trạng thái xử lý
CREATE TABLE IF NOT EXISTS exam_papers (
    paper_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Postgres identity (fix AUTO_INCREMENT)
    essay_id INT NOT NULL REFERENCES exam_essay(essay_id) ON DELETE RESTRICT, -- Thuộc đề tự luận này
    paper_code VARCHAR(20) UNIQUE NOT NULL,                    -- Mã Phách (Khóa chính logic - UNIQUE)
    original_candidate_code VARCHAR(10) NOT NULL,              -- Số Báo Danh đọc được từ scan (SBD_Goc)
    original_exam_paper_code VARCHAR(10) NOT NULL,           -- Mã đề đọc được từ scan (Ma_De_Goc)
    total_sheets_declared INT,								 -- Tổng số tờ thí sinh khai báo (Tong_So_To_Khai)
    total_pages_declared INT, 								-- Tổng số tờ thí sinh khai báo (Tong_So_To_Khai)
    total_pages_scanned INT NOT NULL,						 -- Số trang thực tế được quét vào hệ thống (So_Trang_Scan_Thuc)
    original_file_path VARCHAR(255) NOT NULL,				  -- Đường dẫn file ảnh scan gốc
    anonymized_file_path VARCHAR(255) NOT NULL,				 -- Đường dẫn file ảnh đã che phách (File_Phach_Che)
    validation_status VARCHAR(20) NOT NULL,                    -- Trạng thái: Chưa KD, Lỗi, Đã KD
    validated_by VARCHAR(10),									-- Mã người dùng thực hiện kiểm dò thủ công (Nguoi_Kiem_Do)
    scan_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,				-- Thời điểm scan
    CONSTRAINT CHK_VALIDATION_STATUS CHECK (validation_status IN ('Pending', 'In Progress', 'Error', 'Validated'))
);


-- Khối ảnh cắt ra từ bài thi (từng câu): dùng cho phân công và chấm
CREATE TABLE IF NOT EXISTS exam_blocks (
    block_code VARCHAR(30) PRIMARY KEY,                        -- Mã Block (Khóa chính - thay thế block_id)
    paper_code VARCHAR(20) NOT NULL,                           -- Mã Phách của bài thi chứa block này (FK)
    question_number INT NOT NULL,                              -- Số thứ tự Câu (STT_Cau)
    start_page INT NOT NULL,                                   -- Số trang bắt đầu của câu trả lời (Trang_Bat_Dau)
    end_page INT NOT NULL,                                     -- Số trang kết thúc của câu trả lời (Trang_Ket_Thuc)
    block_image_path VARCHAR(255) NOT NULL,                  -- Đường dẫn file ảnh block tự luận (File_Block_Scan)
    block_status VARCHAR(20) NOT NULL,                         -- Trạng thái: Hợp lệ, Lỗi cấu trúc (Trang_Thai_Block)
    ocr_text TEXT,                                             -- Kết quả OCR
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Khóa ngoại liên kết với exam_papers (BAI_THI_SCAN)
    CONSTRAINT FK_BLOCK_BAITHI FOREIGN KEY (paper_code) 
        REFERENCES exam_papers (paper_code)
        ON DELETE RESTRICT,
    CONSTRAINT CHK_PAGE_RANGE CHECK (start_page <= end_page)
);



-- =====================================================
-- BẢNG BỔ SUNG : validation_errors_log (Ghi nhận lỗi kiểm dò - LOI_KIEM_DO)
-- =====================================================
CREATE TABLE IF NOT EXISTS validation_errors_log (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- ID Lỗi (Khóa chính tự tăng)
    paper_code VARCHAR(20) NOT NULL,                           -- Mã Phách của bài thi bị lỗi (FK)
    error_type VARCHAR(50) NOT NULL,                                   -- Loại Lỗi (Loai_Loi)
    detail_description VARCHAR(255) NOT NULL,                          -- Mô tả chi tiết lỗi (Mo_Ta_Chi_Tiet)
    resolution_status VARCHAR(20) NOT NULL,                      -- Trạng thái: Chưa xử lý, Đã xử lý (Trang_Thai_Xu_Ly)
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                     -- Thời điểm lỗi được ghi nhận (Thoi_Gian_Phat_Hien)
    resolved_by VARCHAR(10),                                           -- Mã người dùng thực hiện sửa lỗi thủ công (Nguoi_Xu_Ly)
    
    -- Khóa ngoại liên kết với exam_papers (BAI_THI_SCAN)
    CONSTRAINT FK_LOG_PAPER FOREIGN KEY (paper_code) 
        REFERENCES exam_papers (paper_code) 
        ON DELETE CASCADE,
        
    CONSTRAINT CHK_RESOLUTION_STATUS CHECK (resolution_status IN ('Pending', 'Resolved', 'Ignored'))
);
-- =====================================================
-- 11) GRADING ASSIGNMENTS/RESULTS/COMPARISONS
-- =====================================================
-- Phân công chấm cho từng khối câu hỏi: người chấm, vòng chấm, ưu tiên, deadline
CREATE TABLE IF NOT EXISTS grading_assignments (
    assignment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID phân công
    block_code VARCHAR(30) NOT NULL REFERENCES exam_blocks(block_code) ON DELETE CASCADE, -- Khối câu hỏi được giao
    examiner_id INT NOT NULL REFERENCES examiners(examiner_id) ON DELETE RESTRICT, -- Cán bộ chấm
    assigned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,               -- Ngày giờ giao việc
    due_date TIMESTAMP NULL,                                         -- Hạn hoàn thành (nếu có)
    status assignment_status_enum DEFAULT 'ASSIGNED',                -- Trạng thái phân công
    round_number INT DEFAULT 1,                                      -- Vòng chấm (1/2/3)
    comparison_group VARCHAR(20),                                    -- Nhóm so sánh (phục vụ đối chiếu)
    priority priority_enum DEFAULT 'MEDIUM',                         -- Mức độ ưu tiên
    assigned_by INT NOT NULL REFERENCES users(user_id)               -- Người giao việc
);

-- Kết quả chấm điểm cho từng phân công: điểm, tiêu chí sử dụng, thời gian chấm
CREATE TABLE IF NOT EXISTS grading_results (
    result_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- ID kết quả chấm
    assignment_id INT NOT NULL REFERENCES grading_assignments(assignment_id) ON DELETE CASCADE, -- Liên kết phân công
    block_code VARCHAR(30) NOT NULL REFERENCES exam_blocks(block_code) ON DELETE CASCADE, -- Khối câu hỏi
    examiner_id INT NOT NULL REFERENCES examiners(examiner_id) ON DELETE RESTRICT, -- Người chấm
    question_number INT NOT NULL,                                    -- Câu số
    score DECIMAL(4,2) NOT NULL,                                     -- Điểm cho câu
    max_score DECIMAL(4,2) NOT NULL,                                 -- Điểm tối đa
    comments TEXT,                                                   -- Nhận xét của giám khảo
    grading_criteria_used JSONB,                                     -- Tiêu chí thực tế áp dụng (log)
    grading_time INT,                                                -- Thời gian chấm (giây)
    is_final BOOLEAN DEFAULT FALSE,                                  -- Có phải kết quả cuối cùng không
    graded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                    -- Thời điểm chấm
);

-- Bảng so sánh kết quả chấm giữa các giám khảo: chọn điểm đồng thuận
CREATE TABLE IF NOT EXISTS grading_comparisons (
    comparison_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID đối chiếu
    block_code VARCHAR(30) NOT NULL REFERENCES exam_blocks(block_code) ON DELETE CASCADE, -- Khối câu hỏi
    comparison_group VARCHAR(20) NOT NULL,                           -- Nhóm so sánh
    result1_id INT NOT NULL REFERENCES grading_results(result_id) ON DELETE CASCADE, -- Kết quả 1
    result2_id INT NOT NULL REFERENCES grading_results(result_id) ON DELETE CASCADE, -- Kết quả 2
    result3_id INT REFERENCES grading_results(result_id) ON DELETE CASCADE,          -- Kết quả 3 (nếu có)
    is_consensus BOOLEAN DEFAULT FALSE,                              -- Đã đồng thuận chưa
    final_score DECIMAL(4,2),                                        -- Điểm cuối được chọn
    final_result_id INT REFERENCES grading_results(result_id) ON DELETE SET NULL, -- Bản ghi kết quả cuối
    compared_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                  -- Thời điểm đối chiếu
);


-- =====================================================
-- 12) FINAL SCORES
-- =====================================================
-- Điểm cuối cùng mỗi môn của mỗi thí sinh: tổng hợp essay + mcq
CREATE TABLE IF NOT EXISTS final_scores (
    score_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- ID điểm cuối
    candidate_id INT NOT NULL REFERENCES candidates(candidate_id) ON DELETE RESTRICT, -- Thí sinh
    subject_id INT NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,       -- Môn thi
    registration_id INT NOT NULL REFERENCES candidate_exam_registrations(registration_id) ON DELETE RESTRICT, -- Đăng ký
    paper_id INT REFERENCES exam_papers(paper_id) ON DELETE SET NULL, -- Bài tự luận liên quan (nếu có)
    attempt_id INT REFERENCES mcq_attempts(attempt_id) ON DELETE SET NULL, -- Phiên MCQ liên quan (nếu có)
    essay_score DECIMAL(5,2) DEFAULT 0.00,                           -- Điểm tự luận
    mcq_score DECIMAL(5,2) DEFAULT 0.00,                             -- Điểm trắc nghiệm
    total_score DECIMAL(5,2) NOT NULL,                               -- Tổng điểm
    grade grade_enum,                                                -- Xếp loại
    status final_status_enum DEFAULT 'DRAFT',                        -- Trạng thái điểm
    finalized_by INT NOT NULL REFERENCES users(user_id),             -- Người chốt điểm
    finalized_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                -- Thời điểm chốt
    published_at TIMESTAMP NULL,                                     -- Thời điểm công bố (nếu có)
    CONSTRAINT unique_candidate_subject_registration UNIQUE (candidate_id, subject_id, registration_id)
);


-- =====================================================
-- 13) STATISTICS
-- =====================================================
-- Thống kê hiệu suất chấm theo giám khảo/ngày
CREATE TABLE IF NOT EXISTS grading_statistics (
    stat_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- ID thống kê
    examiner_id INT NOT NULL REFERENCES examiners(examiner_id) ON DELETE CASCADE, -- Giám khảo
    subject_id INT NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,   -- Môn
    total_blocks_assigned INT DEFAULT 0,                              -- Tổng khối được giao
    total_blocks_graded INT DEFAULT 0,                                -- Tổng khối đã chấm
    avg_grading_time INT,                                            -- Thời gian chấm trung bình (giây)
    total_grading_time INT,                                          -- Tổng thời gian chấm (giây)
    consistency_rate DECIMAL(5,2),                                   -- Tỉ lệ đồng thuận/nhất quán (%)
    productivity_score DECIMAL(5,2),                                 -- Điểm hiệu suất tổng hợp
    date DATE NOT NULL,                                              -- Ngày thống kê
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);

-- Thống kê chất lượng câu hỏi trắc nghiệm (chỉ số đo lường)
CREATE TABLE IF NOT EXISTS question_statistics (
    stat_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- ID thống kê câu hỏi
    question_id INT NOT NULL REFERENCES mcq_questions(question_id) ON DELETE CASCADE, -- Câu hỏi
    total_attempts INT DEFAULT 0,                                    -- Số lượt làm
    correct_answers INT DEFAULT 0,                                   -- Số lượt trả lời đúng
    difficulty_index DECIMAL(4,3),                                   -- Chỉ số độ khó
    discrimination_index DECIMAL(4,3),                               -- Chỉ số phân biệt
    reliability_coefficient DECIMAL(4,3),                            -- Hệ số tin cậy
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- Thời điểm tạo
);

-- Nhật ký nhập/xuất dữ liệu: theo dõi tiến trình, số bản ghi, lỗi
CREATE TABLE IF NOT EXISTS import_export_logs (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         -- ID log
    operation_type operation_type_enum NOT NULL,                     -- Loại thao tác: IMPORT/EXPORT
    table_name VARCHAR(50) NOT NULL,                                 -- Bảng tác động
    file_path VARCHAR(500),                                          -- Đường dẫn file
    file_type VARCHAR(10),                                           -- Loại file (csv/xlsx/json...)
    total_records INT DEFAULT 0,                                     -- Tổng bản ghi trong file
    success_records INT DEFAULT 0,                                   -- Số bản ghi thành công
    error_records INT DEFAULT 0,                                     -- Số bản ghi lỗi
    status operation_status_enum DEFAULT 'PROCESSING',               -- Trạng thái xử lý
    error_details JSONB,                                             -- Chi tiết lỗi (JSONB)
    operation_by INT NOT NULL REFERENCES users(user_id),             -- Người thực hiện
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                  -- Bắt đầu lúc
    completed_at TIMESTAMP NULL                                      -- Kết thúc lúc
);


-- =====================================================
-- 14) TRIGGERS - TỰ ĐỘNG CẬP NHẬT UPDATED_AT
-- =====================================================
-- Trigger cho bảng roles: Tự động update updated_at khi có UPDATE
DROP TRIGGER IF EXISTS update_roles_updated_at ON roles;
CREATE TRIGGER update_roles_updated_at
BEFORE UPDATE ON roles
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Trigger cho bảng users: Tự động update updated_at khi có UPDATE
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Trigger cho bảng registrations: Tự động update updated_at khi có UPDATE
DROP TRIGGER IF EXISTS update_registrations_updated_at ON candidate_exam_registrations;
CREATE TRIGGER update_registrations_updated_at
BEFORE UPDATE ON candidate_exam_registrations
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- =====================================================
-- 15) INDEXES
-- =====================================================
-- Các chỉ mục phục vụ truy vấn nhanh dựa trên các trường thường lọc/tìm kiếm.
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);

CREATE INDEX IF NOT EXISTS idx_candidates_code ON candidates(candidate_code);
CREATE INDEX IF NOT EXISTS idx_candidates_user ON candidates(user_id);
CREATE INDEX IF NOT EXISTS idx_candidates_identity ON candidates(identity_card);

CREATE INDEX IF NOT EXISTS idx_examiners_code ON examiners(examiner_code);
CREATE INDEX IF NOT EXISTS idx_examiners_user ON examiners(user_id);

CREATE INDEX IF NOT EXISTS idx_registrations_candidate ON candidate_exam_registrations(candidate_id);
CREATE INDEX IF NOT EXISTS idx_registrations_subject ON candidate_exam_registrations(subject_id);
CREATE INDEX IF NOT EXISTS idx_registrations_status ON candidate_exam_registrations(status);
CREATE INDEX IF NOT EXISTS idx_registrations_date ON candidate_exam_registrations(registration_date);

CREATE INDEX IF NOT EXISTS idx_subjects_code ON subjects(subject_code);

CREATE INDEX IF NOT EXISTS idx_exam_essay_code ON exam_essay(exam_code);
CREATE INDEX IF NOT EXISTS idx_exam_essay_subject ON exam_essay(subject_id);

CREATE INDEX IF NOT EXISTS idx_exam_mcq_code ON exam_mcq(exam_code);
CREATE INDEX IF NOT EXISTS idx_exam_mcq_subject ON exam_mcq(subject_id);

CREATE INDEX IF NOT EXISTS idx_exam_papers_code ON exam_papers(paper_code);
CREATE INDEX IF NOT EXISTS idx_exam_papers_candidate ON exam_papers(original_candidate_code);
CREATE INDEX IF NOT EXISTS idx_exam_papers_status ON exam_papers(validation_status);

CREATE INDEX IF NOT EXISTS idx_exam_blocks_paper ON exam_blocks(paper_code);
CREATE INDEX IF NOT EXISTS idx_exam_blocks_status ON exam_blocks(block_status);
CREATE INDEX IF NOT EXISTS idx_exam_blocks_question ON exam_blocks(question_number);

CREATE INDEX IF NOT EXISTS idx_grading_assignments_examiner ON grading_assignments(examiner_id);
CREATE INDEX IF NOT EXISTS idx_grading_assignments_block ON grading_assignments(block_code);
CREATE INDEX IF NOT EXISTS idx_grading_assignments_status ON grading_assignments(status);
CREATE INDEX IF NOT EXISTS idx_grading_assignments_round ON grading_assignments(round_number);

CREATE INDEX IF NOT EXISTS idx_grading_results_assignment ON grading_results(assignment_id);
CREATE INDEX IF NOT EXISTS idx_grading_results_examiner ON grading_results(examiner_id);
CREATE INDEX IF NOT EXISTS idx_grading_results_final ON grading_results(is_final);

CREATE INDEX IF NOT EXISTS idx_final_scores_candidate ON final_scores(candidate_id);
CREATE INDEX IF NOT EXISTS idx_final_scores_subject ON final_scores(subject_id);
CREATE INDEX IF NOT EXISTS idx_final_scores_status ON final_scores(status);

CREATE INDEX IF NOT EXISTS idx_mcq_attempts_candidate ON mcq_attempts(candidate_id);
CREATE INDEX IF NOT EXISTS idx_mcq_attempts_schedule ON mcq_attempts(id_schedule);
CREATE INDEX IF NOT EXISTS idx_mcq_attempts_status ON mcq_attempts(status);

CREATE INDEX IF NOT EXISTS idx_cheating_alerts_attempt ON cheating_alerts(attempt_id);
CREATE INDEX IF NOT EXISTS idx_cheating_alerts_time ON cheating_alerts(alert_time);

CREATE INDEX IF NOT EXISTS idx_history_answers_attempt ON history_answers(attempt_id);
CREATE INDEX IF NOT EXISTS idx_history_answers_question ON history_answers(question_id);



-- =====================================================
-- END OF SCHEMA
-- =====================================================
